const translations = {
  ru: {
    'nav-home': 'Главная',
    'nav-menu': 'Меню',
    'nav-special': 'Доставка и оплата',
    'nav-about': 'О нас',
    'nav-contact': 'Контакты',
    'search-placeholder': 'Поиск блюд...',
    'order-online': 'Заказать доставку',
    'hero-subtitle': 'Вкусный фастфуд',
    'hero-title-part1': 'Бургеры ',
    'hero-title-part2': '  `и  вкусные',
    'hero-title-part3': ' `блюда',
    'hero-description': 'Кафе SaFar предлагает качественный фастфуд с местными ингредиентами и быстрой доставкой в Пенджикенте.',
    'view-menu': 'Посмотреть меню',
    'menu-subtitle': 'Наше меню',
    'menu-title': 'Вкусный фастфуд',
    'menu-description': 'Ознакомьтесь с нашим меню: от сочных бургеров до хрустящих стрипсов и прохладительных напитков.',
    'tab-all': 'Все',
    'tab-combo': 'Комбо',
    'tab-burgers': 'Бургеры',
    'tab-hotdogs': 'Хот-доги',
    'tab-strips': 'Стрипсы',
    'tab-sauces': 'Соусы',
    'tab-drinks': 'Напитки',
    'tab-pizza': 'Пицца',
    'tab-salads': 'Салаты',
    'tab-other': 'Другое',
    'badge-hit': 'Хит продаж',
    'category-combo': 'Комбо',
    'name-combo1': 'Комбо Бургер 5 в 1',
    'desc-combo1': '1 Чикенбургер, 125гр картошка фри, 250гр микс, 1шт соус на выбор, 1 шт кола или Фанта 0.5.',
    'name-combo2': 'Комбо 3 в 1',
    'desc-combo2': '1 Чикенбургер, 125гр картошка фри, 1 шт Кола или Фанта 0.5.',
    'name-combo3': 'Комbo X 3 в 1',
    'desc-combo3': '1 Гамбургер говяжий, 125гр картошка фри, 1 шт кола или Фанта 0.5.',
    'name-combo4': 'Комбо Асия',
    'desc-combo4': '125гр байтси, 70гр картошка фри, 2шт жареная сосиска, 1шт сок 200мл, 1шт соус на выбор.',
    'name-combo5': 'Комбо 5 в 1',
    'desc-combo5': '1 шт булочка с кунжутом, 250гр микс порция, 125гр картошка фри, 1шт соус на выбор, 1 шт кола или Фанта 0.5.',
    'name-combo6': 'Френд Бокс',
    'desc-combo6': '1 Гамбургер говяжий, 1 Чикенбургер, 125гр картошка фри, 250гр микс порция, 2 шт соуса на выбор, 1 шт Rc колa 1л.',
    'name-combo7': 'Баскет Комбо 2X',
    'desc-combo7': '2 по 250гр микс порция, 2 по 125гр картошка фри, 2 шт соус на выбор, 2 шт кола или Фанта 0.5.',
    'category-fri': 'Фри',
    'name-fri1': 'Фри с сосиской и соусом',
    'desc-fri1': '150гр Картофель фри, 2шт сосиска и 2 вида соуса на выбор.',
    'name-fri2': 'Фри с тушеным мясом',
    'desc-fri2': '150гр Картофель фри, 70гр тушеного мяса на выбор(говяжий/куриные).',
    'name-fri3': 'Фри с соусом',
    'desc-fri3': '150гр картофель фри, 2 вида соуса на выбор.',
    'name-fri4': 'Картофель по-деревенски',
    'desc-fri4': '125гр Картофель по-деревенски.',
    'name-fri5': 'Картошка Фри',
    'desc-fri5': '125гр порция картофеля фри.',
    'badge-popular': 'Популярное',
    'category-strips': 'Стрипсы',
    'name-strips1': 'Баскет ножки 1КГ',
    'desc-strips1': 'Маленькие куриные ножки в хрустящей панировке. Средней остроты.',
    'name-strips2': 'Ножки 250ГР',
    'desc-strips2': 'Сочные куриные ножки в порционной упаковке. Средней остроты.',
    'name-strips3': 'Баскет крылышки 1кг',
    'desc-strips3': 'Куриные крылышки в хрустящей панировке. Средней остроты.',
    'name-strips4': 'Крылышки 250гр',
    'desc-strips4': 'Куриные стрипсы в порционной упаковке.',
    'name-strips5': 'Баскет стрипцы 1кг',
    'desc-strips5': 'Большая порция хрустящих байтсов. Не острая.',
    'name-strips6': 'Наггетсы 250гр',
    'desc-strips6': 'Куриные наггетсы в порционной упаковке. Не острая.',
    'name-strips8': 'Баскет наггетсы 1кг',
    'desc-strips8': 'Большая порция куриных наггетсов. Не острая.',
    'name-strips9': 'Крылышки 250гр',
    'desc-strips9': 'Куриные крылышки в порционной упаковке.',
    'name-strips10': 'Микс 250гр',
    'desc-strips10': 'Микс порция, состоит из куриных ножек, крылышек, стрипсов и сочных байтсов.',
    'name-strips11': 'Баскет микс 1кг',
    'desc-strips11': 'Большая порция микса из куриных ножек, крылышек, стрипсов и байтсов.',
    'category-burgers': 'Бургеры',
    'name-burger1': 'Двойной Чизбургер',
    'desc-burger1': 'Булочка, соус фирминый майонез, 2 котлеты говяжьи, огурцы , лук , сыр плавленый, помидоры ,соуч чисночный.',
    'name-burger2': 'Бургер в лаваше',
    'desc-burger2': 'Необычный бургер, завернутый в лаваш с говяжьей котлетой, сыром и чипсами Lay\'s.',
    'name-burger3': 'ДаблБургер',
    'desc-burger3': 'Булочка, соус фирминый майонез, 2 котлеты говяжьи, огурцы , лук , сыр плавленый, помидоры ,соуч чисночный.',
    'name-burger5': 'ЧикенБургер',
    'desc-burger5': 'Бургер с куриными стрипсами.',
    'name-burger6': 'Чикен Чиз',
    'desc-burger6': 'Бургер с куриной котлетой и сыром.',
    'name-burger7': 'Биф & Чикен',
    'desc-burger7': 'Бургер с говяжьей и куриной котлетами и сыром.',
    'name-burger8': 'Цезарь Бургер',
    'desc-burger8': 'Бургер с курицей и соусом Цезарь.',
    'name-burger9': 'Чизбургер',
    'desc-burger9': 'Классический бургер с сыром.',
    'name-burger10': 'Гамбургер',
    'desc-burger10': 'Классический гамбургер с сочной котлетой.',
    'name-burger11': 'Panj kent бургер',
    'desc-burger11': 'Классический гамбургер с сочной котлетой.',
    'category-hotdogs': 'Хот-доги',
    'name-hotdog1': 'Хот-дог SaFar',
    'desc-hotdog1': 'Хот-дог с сочной сосиской и соусом.',
    'name-hotdog3': 'Хот-дог Лонгер',
    'desc-hotdog3': 'Длинный хот-дог с сочной сосиской.',
    'name-hotdog5': 'Хот-дог гриль',
    'desc-hotdog5': 'Хот-дог с сосиской, приготовленной на гриле.',
    'name-hotdog6': 'Хот-дог стандарт',
    'desc-hotdog6': 'Классический хот-дог.',
    'name-hotdog7': 'Хот-дог мини',
    'desc-hotdog7': 'Классический хот-дог.',
    'name-hotdog8': 'Хот кебаб',
    'desc-hotdog8': 'Классический хот-дог.',
    'name-hotdog9': 'Хот-дог Panj kent',
    'desc-hotdog9': 'Классический хот-дог.',
    'name-hotdog10': 'Хот-дог BBQ',
    'desc-hotdog10': 'Хот-дог с соусом барбекю.',
    'category-shaverma': 'Шаверма',
    'name-shaverma1': 'Твистер Шаверма',
    'desc-shaverma1': 'Твистер с начинкой из шавермы.',
    'name-shaverma2': 'Твистер',
    'desc-shaverma2': 'Классический твистер с курицей.',
    'name-shaverma3': 'Твистер острый',
    'desc-shaverma3': 'Острый твистер с курицей.',
    'name-shaverma4': 'Твистер шаверма сырный',
    'desc-shaverma4': 'Твистер с шавермой и сыром.',
    'name-shaverma5': 'Твистер  сырный',
    'desc-shaverma5': 'Твистер с шавермой и сыром.',
    'name-shaverma6': 'Тан туни с курицей',
    'desc-shaverma6': 'Твистер с шавермой и сыром.',
    'name-shaverma7': 'Тан туни с говядиной',
    'desc-shaverma7': 'Твистер с шавермой и сыром.',
    'category-pizza': 'Пицца',
    'name-pizza1': 'Пицца Маргарита',
    'desc-pizza1': '30 см',
    'name-pizza2': 'Груша дор блю',
    'desc-pizza2': '30 см',
    'name-pizza3': 'Гавайский',
    'desc-pizza3': '30см',
    'name-pizza4': 'Курица грибы',
    'desc-pizza4': 'Классическая пицца с томатным соусом, моцареллой и свежими помидорами.',
    'name-pizza5': 'Пеперони',
    'desc-pizza5': 'Классическая пицца с томатным соусом, моцареллой и свежими помидорами.',
    'name-pizza6': 'Safar фирминый 55см',
    'desc-pizza6': 'Классическая пицца с томатным соусом, моцареллой и свежими помидорами.',
    'name-pizza7': '4 сезона',
    'desc-pizza7': 'Классическая пицца с томатным соусом, моцареллой и свежими помидорами.',
    'name-pizza8': 'Пицца Маргарита',
    'desc-pizza8': 'Классическая пицца с томатным соусом, моцареллой и свежими помидорами.',
    'name-pizza9': '4 сыра',
    'desc-pizza9': 'Классическая пицца с томатным соусом, моцареллой и свежими помидорами.',
    'name-pizza10': 'Мясная',
    'desc-pizza10': 'Классическая пицца с томатным соусом, моцареллой и свежими помидорами.',
    'name-pizza11': 'Цыплёнок ранч',
    'desc-pizza11': 'Классическая пицца с томатным соусом, моцареллой и свежими помидорами.',
    'name-pizza12': 'Трюфельная',
    'desc-pizza12': 'Классическая пицца с томатным соусом, моцареллой и свежими помидорами.',
    'category-salads': 'Салаты',
    'name-salad1': 'Салат греческий',
    'desc-salad1': 'ририр',
    'name-salad2': 'Салат японский',
    'desc-salad2': 'ририр',
    'name-salad3': 'Салат Цезарь с курицей',
    'desc-salad3': 'ририр',
    'name-salad4': 'Салат из баклажанов',
    'desc-salad4': 'ририр',
    'category-drinks': 'Напитки',
    'name-drink1': 'Gorilla 0.33 мл',
    'desc-drink1': 'Энергетический напиток.',
    'name-drink2': 'Adrenaline 0.25 мл',
    'desc-drink2': 'Энергетический напиток.',
    'name-drink3': 'RC кола 1 л',
    'desc-drink3': 'Газированный напиток.',
    'name-drink4': 'Pepsi 1 л',
    'desc-drink4': 'Газированный напиток.',
    'name-drink5': 'Мохито 0.5 л',
    'desc-drink5': 'Освежающий напиток с различными вкусами.',
    'name-drink6': 'Bon aqua 0.5 л',
    'desc-drink6': 'Питьевая вода.',
    'name-drink7': 'Чай фюсти 0.5 л',
    'desc-drink7': 'Холодный чай.',
    'name-drink8': 'Натуральный Сок пико 1 л',
    'desc-drink8': 'Фруктовый сок.',
    'name-drink9': 'Fanta 1 л',
    'desc-drink9': 'Газированный напиток.',
    'name-drink10': 'Coca Cola 0.5',
    'desc-drink10': 'Газированный напиток.',
    'name-drink11': 'Тропик 0.5',
    'desc-drink11': 'Освежающий напиток. Сочный апельсин.',
    'category-sauces': 'Соусы',
    'name-sauce1': 'Соус чесночный',
    'desc-sauce1': 'Чесночный соус 35гр.',
    'name-sauce2': 'Соус острый',
    'desc-sauce2': 'Острый соус 35гр.',
    'name-sauce3': 'Соус сырный',
    'desc-sauce3': 'Сырный соус 35гр.',
    'category-other': 'Другое',
    'name-other1': 'Котлета из говядины 100гр',
    'desc-other1': 'Котлета из говядины.',
    'name-other2': 'Сыр плавленый 1шт',
    'desc-other2': 'Плавленый сыр.',
    'name-other3': 'Перец халапеньо 15гр',
    'desc-other3': 'Острый маринованный перец халапеньо.',
    'name-other4': 'Булочка',
    'desc-other4': 'Свежая булочка для бургеров.',
    'special-subtitle': 'Доставка и оплата',
    'special-title': 'Как заказать и оплатить',
    'special-description': 'Быстрая доставка в пределах Пенджикента и удобные способы оплаты для вашего комфорта.',
    'delivery-title': 'Доставка',
    'delivery-subtitle': 'С 9:00 до 22:00',
    'delivery-feature1': 'Бесплатная доставка при заказе от 50 TJS',
    'delivery-feature2': 'Доставка только в пределах Пенджикента',
    'delivery-feature3': 'Заказы принимаются по телефону или через соцсети',
    'delivery-feature4': 'Контакты для доставки: +992 928 082 552, +992 970 882 552',
    'order-delivery': 'Заказать доставку',
    'badge-fast': 'Быстро и удобно',
    'payment-title': 'Оплата и техподдержка',
    'payment-subtitle': 'Удобные способы оплаты',
    'payment-feature1': 'Оплата через Алиф',
    'payment-feature2': 'Оплата через Душанбе Сити',
    'payment-feature3': 'Оплата наличными при получении',
    'payment-feature4': 'Техподдержка: WhatsApp +7(996)5450272',
    'contact-support': 'Связаться с поддержкой',
    'badge-always': 'Всегда на связи',
    'about-subtitle': 'Наша история',
    'about-title': 'Кафе SaFar',
    'about-text1': 'Кафе SaFar в Пенджикенте – это место, где фастфуд превращается в искусство. Мы используем свежие местные ингредиенты, чтобы создавать вкусные и качественные блюда.',
    'about-text2': 'Мы гордимся быстрой доставкой и вниманием к каждому заказу. От сочных бургеров до хрустящих стрипсов – всё готовится с душой.',
    'about-feature-title1': 'Свежие ингредиенты',
    'about-feature-text1': 'Используем только местные продукты высокого качества.',
    'about-feature-title2': 'Уникальные рецепты',
    'about-feature-text2': 'Вкусные блюда, созданные с заботой.',
    'about-feature-title3': 'Быстрая доставка',
    'about-feature-text3': 'Доставка в пределах Пенджикента от 50 TJS бесплатно.',
    'about-feature-title4': 'С любовью',
    'about-feature-text4': 'Каждое блюдо приготовлено с заботой.',
    'about-badge': 'С 2023 года',
    'order-title': 'Готовы попробовать вкусный фастфуд?',
    'order-text': 'Закажите онлайн с доставкой или самовывозом и наслаждайтесь нашими блюдами дома или в офисе.',
    'order-btn': 'Заказать',
    'footer-text': 'Кафе SaFar – это вкусный фастфуд с местными ингредиентами и быстрой доставкой в Пенджикенте.',
    'footer-heading1': 'Быстрые ссылки',
    'footer-heading2': 'Часы работы',
    'opening-cafe': 'Кафе: 08:00 - 23:00',
    'opening-delivery': 'Доставка: 09:00 - 22:00',
    'footer-heading3': 'Контакты',
    'contact-address': 'Проспект Рудаки 112, Пенджикент, Таджикистан',
    'contact-support': 'Техподдержка',
    'footer-copyright': '&copy; 2025 Кафе SaFar. |  Разработка <a href="https://t.me/xalilov_uc">Sino IT </a>',
    'cart-title': 'Ваша корзина',
    'cart-total': 'Итого:',
    'label-name': 'Ваше имя',
    'placeholder-name': 'напишите свое имя',
    'label-phone': 'Телефон',
    'label-order-type': 'Тип заказа',
    'button-delivery': 'Доставка',
    'button-pickup': 'Самовывоз',
    'label-address': 'Адрес доставки',
    'placeholder-address': 'напишите свой адрес',
    'label-pickup': 'Место самовывоза',
    'pickup-option1': 'Болои дедсати сказка',
    'pickup-option2': 'Пеши мактаби 15',
    'pickup-option3': 'Ру ба руи мехру мухаббат пиццерия',
    'label-payment': 'Способ оплаты',
    'payment-cash': 'Наличные',
    'payment-ds': 'Душанбе Сити',
    'payment-alif': 'Алиф',
    'label-comments': 'Комментарий к заказу',
    'placeholder-comments': 'напишите комментари по поводу заказа(можете пропустить!)',
    'order-total': 'К оплате:',
    'submit-order': 'Оформить заказ',
    "login": "Вход",
  },
  en: {
    'nav-home': 'Home',
    'nav-menu': 'Menu',
    'nav-special': 'Delivery and Payment',
    'nav-about': 'About Us',
    'nav-contact': 'Contacts',
    'search-placeholder': 'Search dishes...',
    'order-online': 'Order Online',
    'hero-subtitle': 'Delicious Fast Food',
    'hero-title-part1': 'Burgers ',
    'hero-title-part2': ' `and delicious',
    'hero-title-part3': ' `dishes',
    'hero-description': 'Cafe SaFar offers high-quality fast food with local ingredients and fast delivery in Penjikent.',
    'view-menu': 'View Menu',
    'menu-subtitle': 'Our Menu',
    'menu-title': 'Delicious Fast Food',
    'menu-description': 'Check out our menu: from juicy burgers to crispy strips and refreshing drinks.',
    'tab-all': 'All',
    'tab-combo': 'Combo',
    'tab-burgers': 'Burgers',
    'tab-hotdogs': 'Hot Dogs',
    'tab-strips': 'Strips',
    'tab-sauces': 'Sauces',
    'tab-drinks': 'Drinks',
    'tab-pizza': 'Pizza',
    'tab-salads': 'Salads',
    'tab-other': 'Other',
    'badge-hit': 'Best Seller',
    'category-combo': 'Combo',
    'name-combo1': 'Combo Burger 5 in 1',
    'desc-combo1': '1 Chickenburger, 125g french fries, 250g mix, 1pc sauce of choice, 1 pc cola or Fanta 0.5.',
    'name-combo2': 'Combo 3 in 1',
    'desc-combo2': '1 Chickenburger, 125g french fries, 1 pc Cola or Fanta 0.5.',
    'name-combo3': 'Combo X 3 in 1',
    'desc-combo3': '1 Beef Hamburger, 125g french fries, 1 pc cola or Fanta 0.5.',
    'name-combo4': 'Combo Asia',
    'desc-combo4': '125g bites, 70g french fries, 2pc fried sausage, 1pc juice 200ml, 1pc sauce of choice.',
    'name-combo5': 'Combo 5 in 1',
    'desc-combo5': '1 pc sesame bun, 250g mix portion, 125g french fries, 1pc sauce of choice, 1 pc cola or Fanta 0.5.',
    'name-combo6': 'Friend Box',
    'desc-combo6': '1 Beef Hamburger, 1 Chickenburger, 125g french fries, 250g mix portion, 2 pc sauces of choice, 1 pc Rc cola 1l.',
    'name-combo7': 'Basket Combo 2X',
    'desc-combo7': '2 x 250g mix portion, 2 x 125g french fries, 2 pc sauces of choice, 2 pc cola or Fanta 0.5.',
    'category-fri': 'Fries',
    'name-fri1': 'Fries with Sausage and Sauce',
    'desc-fri1': '150g French fries, 2pc sausage and 2 types of sauce of choice.',
    'name-fri2': 'Fries with Stewed Meat',
    'desc-fri2': '150g French fries, 70g stewed meat of choice (beef/chicken).',
    'name-fri3': 'Fries with Sauce',
    'desc-fri3': '150g french fries, 2 types of sauce of choice.',
    'name-fri4': 'Country-Style Potatoes',
    'desc-fri4': '125g Country-style potatoes.',
    'name-fri5': 'French Fries',
    'desc-fri5': '125g portion of french fries.',
    'badge-popular': 'Popular',
    'category-strips': 'Strips',
    'name-strips1': 'Basket Legs 1KG',
    'desc-strips1': 'Small chicken legs in crispy breading. Medium spiciness.',
    'name-strips2': 'Legs 250G',
    'desc-strips2': 'Juicy chicken legs in portion packaging. Medium spiciness.',
    'name-strips3': 'Basket Wings 1kg',
    'desc-strips3': 'Chicken wings in crispy breading. Medium spiciness.',
    'name-strips4': 'Strips 250g',
    'desc-strips4': 'Chicken strips in portion packaging.',
    'name-strips5': 'Basket Bites 1kg',
    'desc-strips5': 'Large portion of crispy bites. Not spicy.',
    'name-strips6': 'Nuggets 250g',
    'desc-strips6': 'Chicken nuggets in portion packaging. Not spicy.',
    'name-strips8': 'Basket Nuggets 1kg',
    'desc-strips8': 'Large portion of chicken nuggets. Not spicy.',
    'name-strips9': 'Wings 250g',
    'desc-strips9': 'Chicken wings in portion packaging.',
    'name-strips10': 'Mix 250g',
    'desc-strips10': 'Mix portion, consisting of chicken legs, wings, strips and juicy bites.',
    'name-strips11': 'Basket Mix 1kg',
    'desc-strips11': 'Large portion of mix from chicken legs, wings, strips and bites.',
    'category-burgers': 'Burgers',
    'name-burger1': 'Double Cheeseburger',
    'desc-burger1': 'Bun, signature mayonnaise sauce, 2 beef patties, cucumbers, onion, melted cheese, tomatoes, garlic sauce.',
    'name-burger2': 'Burger in Lavash',
    'desc-burger2': 'Unusual burger wrapped in lavash with beef patty, cheese and Lay\'s chips.',
    'name-burger3': 'DoubleBurger',
    'desc-burger3': 'Bun, signature mayonnaise sauce, 2 beef patties, cucumbers, onion, melted cheese, tomatoes, garlic sauce.',
    'name-burger5': 'ChickenBurger',
    'desc-burger5': 'Burger with chicken strips.',
    'name-burger6': 'Chicken Cheese',
    'desc-burger6': 'Burger with chicken patty and cheese.',
    'name-burger7': 'Beef & Chicken',
    'desc-burger7': 'Burger with beef and chicken patties and cheese.',
    'name-burger8': 'Caesar Burger',
    'desc-burger8': 'Burger with chicken and Caesar sauce.',
    'name-burger9': 'Cheeseburger',
    'desc-burger9': 'Classic burger with cheese.',
    'name-burger10': 'Hamburger',
    'desc-burger10': 'Classic hamburger with juicy patty.',
    'name-burger11': 'Panj kent burger',
    'desc-burger11': 'Classic hamburger with juicy patty.',
    'category-hotdogs': 'Hot Dogs',
    'name-hotdog1': 'Hot Dog SaFar',
    'desc-hotdog1': 'Hot dog with juicy sausage and sauce.',
    'name-hotdog3': 'Hot Dog Longer',
    'desc-hotdog3': 'Long hot dog with juicy sausage.',
    'name-hotdog5': 'Hot Dog Grill',
    'desc-hotdog5': 'Hot dog with sausage cooked on grill.',
    'name-hotdog6': 'Hot Dog Standard',
    'desc-hotdog6': 'Classic hot dog.',
    'name-hotdog7': 'Hot Dog Mini',
    'desc-hotdog7': 'Classic hot dog.',
    'name-hotdog8': 'Hot Kebab',
    'desc-hotdog8': 'Classic hot dog.',
    'name-hotdog9': 'Hot Dog Panj kent',
    'desc-hotdog9': 'Classic hot dog.',
    'name-hotdog10': 'Hot Dog BBQ',
    'desc-hotdog10': 'Hot dog with BBQ sauce.',
    'category-shaverma': 'Shaverma',
    'name-shaverma1': 'Twister Shaverma',
    'desc-shaverma1': 'Twister with shaverma filling.',
    'name-shaverma2': 'Twister',
    'desc-shaverma2': 'Classic twister with chicken.',
    'name-shaverma3': 'Twister Spicy',
    'desc-shaverma3': 'Spicy twister with chicken.',
    'name-shaverma4': 'Twister Shaverma Cheesy',
    'desc-shaverma4': 'Twister with shaverma and cheese.',
    'name-shaverma5': 'Twister Cheesy',
    'desc-shaverma5': 'Twister with shaverma and cheese.',
    'name-shaverma6': 'Tan Tuni with Chicken',
    'desc-shaverma6': 'Twister with shaverma and cheese.',
    'name-shaverma7': 'Tan Tuni with Beef',
    'desc-shaverma7': 'Twister with shaverma and cheese.',
    'category-pizza': 'Pizza',
    'name-pizza1': 'Pizza Margherita',
    'desc-pizza1': '30 cm',
    'name-pizza2': 'Pear Dor Blue',
    'desc-pizza2': '30 cm',
    'name-pizza3': 'Hawaiian',
    'desc-pizza3': '30cm',
    'name-pizza4': 'Chicken Mushrooms',
    'desc-pizza4': 'Classic pizza with tomato sauce, mozzarella and fresh tomatoes.',
    'name-pizza5': 'Pepperoni',
    'desc-pizza5': 'Classic pizza with tomato sauce, mozzarella and fresh tomatoes.',
    'name-pizza6': 'Safar Signature 55cm',
    'desc-pizza6': 'Classic pizza with tomato sauce, mozzarella and fresh tomatoes.',
    'name-pizza7': '4 Seasons',
    'desc-pizza7': 'Classic pizza with tomato sauce, mozzarella and fresh tomatoes.',
    'name-pizza8': 'Pizza Margherita',
    'desc-pizza8': 'Classic pizza with tomato sauce, mozzarella and fresh tomatoes.',
    'name-pizza9': '4 Cheeses',
    'desc-pizza9': 'Classic pizza with tomato sauce, mozzarella and fresh tomatoes.',
    'name-pizza10': 'Meat',
    'desc-pizza10': 'Classic pizza with tomato sauce, mozzarella and fresh tomatoes.',
    'name-pizza11': 'Chicken Ranch',
    'desc-pizza11': 'Classic pizza with tomato sauce, mozzarella and fresh tomatoes.',
    'name-pizza12': 'Truffle',
    'desc-pizza12': 'Classic pizza with tomato sauce, mozzarella and fresh tomatoes.',
    'category-salads': 'Salads',
    'name-salad1': 'Greek Salad',
    'desc-salad1': 'ririr',
    'name-salad2': 'Japanese Salad',
    'desc-salad2': 'ririr',
    'name-salad3': 'Caesar Salad with Chicken',
    'desc-salad3': 'ririr',
    'name-salad4': 'Eggplant Salad',
    'desc-salad4': 'ririr',
    'category-drinks': 'Drinks',
    'name-drink1': 'Gorilla 0.33 ml',
    'desc-drink1': 'Energy drink.',
    'name-drink2': 'Adrenaline 0.25 ml',
    'desc-drink2': 'Energy drink.',
    'name-drink3': 'RC Cola 1 l',
    'desc-drink3': 'Carbonated drink.',
    'name-drink4': 'Pepsi 1 l',
    'desc-drink4': 'Carbonated drink.',
    'name-drink5': 'Mojito 0.5 l',
    'desc-drink5': 'Refreshing drink with various flavors.',
    'name-drink6': 'Bon aqua 0.5 l',
    'desc-drink6': 'Drinking water.',
    'name-drink7': 'Fusti Tea 0.5 l',
    'desc-drink7': 'Cold tea.',
    'name-drink8': 'Natural Pico Juice 1 l',
    'desc-drink8': 'Fruit juice.',
    'name-drink9': 'Fanta 1 l',
    'desc-drink9': 'Carbonated drink.',
    'name-drink10': 'Coca Cola 0.5',
    'desc-drink10': 'Carbonated drink.',
    'name-drink11': 'Tropic 0.5',
    'desc-drink11': 'Refreshing drink. Juicy orange.',
    'category-sauces': 'Sauces',
    'name-sauce1': 'Garlic Sauce',
    'desc-sauce1': 'Garlic sauce 35g.',
    'name-sauce2': 'Spicy Sauce',
    'desc-sauce2': 'Spicy sauce 35g.',
    'name-sauce3': 'Cheese Sauce',
    'desc-sauce3': 'Cheese sauce 35g.',
    'category-other': 'Other',
    'name-other1': 'Beef Patty 100g',
    'desc-other1': 'Beef patty.',
    'name-other2': 'Melted Cheese 1pc',
    'desc-other2': 'Melted cheese.',
    'name-other3': 'Jalapeno Pepper 15g',
    'desc-other3': 'Spicy marinated jalapeno pepper.',
    'name-other4': 'Bun',
    'desc-other4': 'Fresh bun for burgers.',
    'special-subtitle': 'Delivery and Payment',
    'special-title': 'How to Order and Pay',
    'special-description': 'Fast delivery within Penjikent and convenient payment methods for your comfort.',
    'delivery-title': 'Delivery',
    'delivery-subtitle': 'From 9:00 to 22:00',
    'delivery-feature1': 'Free delivery for orders from 50 TJS',
    'delivery-feature2': 'Delivery only within Penjikent',
    'delivery-feature3': 'Orders accepted by phone or through social networks',
    'delivery-feature4': 'Delivery contacts: +992 928 082 552, +992 970 882 552',
    'order-delivery': 'Order Delivery',
    'badge-fast': 'Fast and convenient',
    'payment-title': 'Payment and Support',
    'payment-subtitle': 'Convenient payment methods',
    'payment-feature1': 'Payment via Alif',
    'payment-feature2': 'Payment via Dushanbe City',
    'payment-feature3': 'Cash payment upon receipt',
    'payment-feature4': 'Technical support: WhatsApp +7 (996)5450272',
    'contact-support': 'Contact Support',
    'badge-always': 'Always online',
    'about-subtitle': 'Our Story',
    'about-title': 'Cafe SaFar',
    'about-text1': 'Cafe SaFar in Penjikent is a place where fast food turns into art. We use fresh local ingredients to create delicious and high-quality dishes.',
    'about-text2': 'We pride ourselves on fast delivery and attention to every order. From juicy burgers to crispy strips - everything is prepared with soul.',
    'about-feature-title1': 'Fresh Ingredients',
    'about-feature-text1': 'We use only high-quality local products.',
    'about-feature-title2': 'Unique Recipes',
    'about-feature-text2': 'Delicious dishes created with care.',
    'about-feature-title3': 'Fast Delivery',
    'about-feature-text3': 'Delivery within Penjikent from 50 TJS free.',
    'about-feature-title4': 'With Love',
    'about-feature-text4': 'Every dish is prepared with care.',
    'about-badge': 'Since 2023',
    'order-title': 'Ready to try delicious fast food?',
    'order-text': 'Order online with delivery or pickup and enjoy our dishes at home or in the office.',
    'order-btn': 'Order',
    'footer-text': 'Cafe SaFar is delicious fast food with local ingredients and fast delivery in Penjikent.',
    'footer-heading1': 'Quick Links',
    'footer-heading2': 'Opening Hours',
    'opening-cafe': 'Cafe: 08:00 - 23:00',
    'opening-delivery': 'Delivery: 09:00 - 22:00',
    'footer-heading3': 'Contacts',
    'contact-address': 'Rudaki Avenue 112, Penjikent, Tajikistan',
    'contact-support': '  Technical Support',
    'footer-copyright': '&copy; 2025 Cafe SaFar. | Development <a href="https://t.me/xalilov_uc">Sino IT </a>',
    'cart-title': 'Your Cart',
    'cart-total': 'Total:',
    'label-name': 'Your Name',
    'placeholder-name': 'write your name',
    'label-phone': 'Phone',
    'label-order-type': 'Order Type',
    'button-delivery': 'Delivery',
    'button-pickup': 'Pickup',
    'label-address': 'Delivery Address',
    'placeholder-address': 'write your address',
    'label-pickup': 'Pickup Location',
    'pickup-option1': 'Above the fairy tale kindergarten',
    'pickup-option2': 'In front of school 15',
    'pickup-option3': 'opposite the restaurant mehru muhabat pizzeria',
    'label-payment': 'Payment Method',
    'payment-cash': 'Cash',
    'payment-ds': 'Dushanbe City',
    'payment-alif': 'Alif',
    'label-comments': 'Order Comment',
    'placeholder-comments': 'write a comment about the order (you can skip!)',
    'order-total': 'To pay:',
    'submit-order': 'Place Order',
    "login": "Login",
  },
  tg: {
    'nav-home': 'Асосӣ',
    'nav-menu': 'Меню',
    'nav-special': 'Интиқол ва пардохт',
    'nav-about': 'Дар бораи мо',
    'nav-contact': 'Тамосҳо',
    'search-placeholder': 'Ҷустуҷӯи таомҳо...',
    'order-online': 'Фармоиш онлайн',
    'hero-subtitle': 'Фастфуди болаззат',
    'hero-title-part1': 'Бургерҳо ',
    'hero-title-part2': '  `ва болаззат',
    'hero-title-part3': ' `таомҳо',
    'hero-description': 'Кафе SaFar фастфуди сифатнок бо ингредиентҳои маҳаллӣ ва интиқоли зуд дар Пенҷикент пешниҳод мекунад.',
    'view-menu': 'Менюро дидан',
    'menu-subtitle': 'Менюи мо',
    'menu-title': 'Фастфуди болаззат',
    'menu-description': 'Менюи моро дидан: аз бургерҳои ширин то стрипсҳои хрустящ ва нӯшокиҳои сард.',
    'tab-all': 'Ҳама',
    'tab-combo': 'Комбо',
    'tab-burgers': 'Бургерҳо',
    'tab-hotdogs': 'Хот-догҳо',
    'tab-strips': 'Стрипсҳо',
    'tab-sauces': 'Соусҳо',
    'tab-drinks': 'Нӯшокиҳо',
    'tab-pizza': 'Пицца',
    'tab-salads': 'Салатҳо',
    'tab-other': 'Дигар',
    'badge-hit': 'Хити фурӯш',
    'category-combo': 'Комбо',
    'name-combo1': 'Комбо Бургер 5 дар 1',
    'desc-combo1': '1 Чикенбургер, 125г картошка фри, 250г микс, 1д соус интихобӣ, 1 д кола ё Фанта 0.5.',
    'name-combo2': 'Комбо 3 дар 1',
    'desc-combo2': '1 Чикенбургер, 125г картошка фри, 1 д Кола ё Фанта 0.5.',
    'name-combo3': 'Комбо X 3 дар 1',
    'desc-combo3': '1 Гамбургер говяжӣ, 125г картошка фри, 1 д кола ё Фанта 0.5.',
    'name-combo4': 'Комбо Асия',
    'desc-combo4': '125г байтсӣ, 70г картошка фри, 2д жареная сосиска, 1д сок 200мл, 1д соус интихобӣ.',
    'name-combo5': 'Комбо 5 дар 1',
    'desc-combo5': '1 д булочка бо кунжут, 250г микс порция, 125г картошка фри, 1д соус интихобӣ, 1 д кола ё Фанта 0.5.',
    'name-combo6': 'Френд Бокс',
    'desc-combo6': '1 Гамбургер говяжӣ, 1 Чикенбургер, 125г картошка фри, 250г микс порция, 2 д соусҳо интихобӣ, 1 д Rc кола 1л.',
    'name-combo7': 'Баскет Комбо 2X',
    'desc-combo7': '2 х 250г микс порция, 2 х 125г картошка фри, 2 д соус интихобӣ, 2 д кола ё Фанта 0.5.',
    'category-fri': 'Фри',
    'name-fri1': 'Фри бо сосиска ва соус',
    'desc-fri1': '150г Картофел фри, 2д сосиска ва 2 навъи соус интихобӣ.',
    'name-fri2': 'Фри бо гӯшти тушида',
    'desc-fri2': '150г Картофел фри, 70г гӯшти тушида интихобӣ (говяжӣ/куриные).',
    'name-fri3': 'Фри бо соус',
    'desc-fri3': '150г картофел фри, 2 навъи соус интихобӣ.',
    'name-fri4': 'Картофел бо-деревенски',
    'desc-fri4': '125г Картофел бо-деревенски.',
    'name-fri5': 'Картошка Фри',
    'desc-fri5': '125г порсия картофели фри.',
    'badge-popular': 'Машҳур',
    'category-strips': 'Стрипсҳо',
    'name-strips1': 'Баскет пойҳо 1КГ',
    'desc-strips1': 'Пойҳои хурди куриные дар панировкаи хрустящ. Остротаи миёна.',
    'name-strips2': 'Пойҳо 250Г',
    'desc-strips2': 'Пойҳои ширин куриные дар упаковкаи порсионӣ. Остротаи миёна.',
    'name-strips3': 'Баскет болҳо 1кг',
    'desc-strips3': 'Болҳои куриные дар панировкаи хрустящ. Остротаи миёна.',
    'name-strips4': 'Стрипсҳо 250г',
    'desc-strips4': 'Стрипсҳои куриные дар упаковкаи порсионӣ.',
    'name-strips5': 'Баскет байтсҳо 1кг',
    'desc-strips5': 'Порсияи калон хрустящ байтсҳо. Не острая.',
    'name-strips6': 'Наггетсҳо 250г',
    'desc-strips6': 'Наггетсҳои куриные дар упаковкаи порсионӣ. Не острая.',
    'name-strips8': 'Баскет наггетсҳо 1кг',
    'desc-strips8': 'Порсияи калон наггетсҳои куриные. Не острая.',
    'name-strips9': 'Болҳо 250г',
    'desc-strips9': 'Болҳои куриные дар упаковкаи порсионӣ.',
    'name-strips10': 'Микс 250г',
    'desc-strips10': 'Порсия микс, аз пойҳои куриные, болҳо, стрипсҳо ва байтсҳои ширин.',
    'name-strips11': 'Баскет микс 1кг',
    'desc-strips11': 'Порсияи калон микс аз пойҳои куриные, болҳо, стрипсҳо ва байтсҳо.',
    'category-burgers': 'Бургерҳо',
    'name-burger1': 'Двойной Чизбургер',
    'desc-burger1': 'Булочка, соус фирминий майонез, 2 котлети говяжӣ, огурцы , лук , сыр плавленый, помидоры ,соуч чесночный.',
    'name-burger2': 'Бургер дар лаваш',
    'desc-burger2': 'Бургери ғайриоддӣ, дар лаваш пӯшида бо котлети говяжӣ, сыр ва чипсҳои Lay\'s.',
    'name-burger3': 'ДаблБургер',
    'desc-burger3': 'Булочка, соус фирминий майонез, 2 котлети говяжӣ, огурцы , лук , сыр плавленый, помидоры ,соуч чесночный.',
    'name-burger5': 'ЧикенБургер',
    'desc-burger5': 'Бургер бо стрипсҳои куриные.',
    'name-burger6': 'Чикен Чиз',
    'desc-burger6': 'Бургер бо котлети куриные ва сыр.',
    'name-burger7': 'Биф & Чикен',
    'desc-burger7': 'Бургер бо котлетҳои говяжӣ ва куриные ва сыр.',
    'name-burger8': 'Цезарь Бургер',
    'desc-burger8': 'Бургер бо куриные ва соуси Цезарь.',
    'name-burger9': 'Чизбургер',
    'desc-burger9': 'Бургери классикӣ бо сыр.',
    'name-burger10': 'Гамбургер',
    'desc-burger10': 'Гамбургери классикӣ бо котлети ширин.',
    'name-burger11': 'Panj kent бургер',
    'desc-burger11': 'Гамбургери классикӣ бо котлети ширин.',
    'category-hotdogs': 'Хот-догҳо',
    'name-hotdog1': 'Хот-дог SaFar',
    'desc-hotdog1': 'Хот-дог бо сосискаи ширин ва соус.',
    'name-hotdog3': 'Хот-дог Лонгер',
    'desc-hotdog3': 'Хот-доги дароз бо сосискаи ширин.',
    'name-hotdog5': 'Хот-дог гриль',
    'desc-hotdog5': 'Хот-дог бо сосиска, дар гриль пухташуда.',
    'name-hotdog6': 'Хот-дог стандарт',
    'desc-hotdog6': 'Хот-доги классикӣ.',
    'name-hotdog7': 'Хот-дог мини',
    'desc-hotdog7': 'Хот-доги классикӣ.',
    'name-hotdog8': 'Хот кебаб',
    'desc-hotdog8': 'Хот-доги классикӣ.',
    'name-hotdog9': 'Хот-дог Panj kent',
    'desc-hotdog9': 'Хот-доги классикӣ.',
    'name-hotdog10': 'Хот-дог BBQ',
    'desc-hotdog10': 'Хот-дог бо соуси барбекю.',
    'category-shaverma': 'Шаверма',
    'name-shaverma1': 'Твистер Шаверма',
    'desc-shaverma1': 'Твистер бо пуркунии шаверма.',
    'name-shaverma2': 'Твистер',
    'desc-shaverma2': 'Твистери классикӣ бо куриные.',
    'name-shaverma3': 'Твистер острый',
    'desc-shaverma3': 'Твистери острый бо куриные.',
    'name-shaverma4': 'Твистер шаверма сырный',
    'desc-shaverma4': 'Твистер бо шаверма ва сыр.',
    'name-shaverma5': 'Твистер сырный',
    'desc-shaverma5': 'Твистер бо шаверма ва сыр.',
    'name-shaverma6': 'Тан туни бо куриные',
    'desc-shaverma6': 'Твистер бо шаверма ва сыр.',
    'name-shaverma7': 'Тан туни бо говядиной',
    'desc-shaverma7': 'Твистер бо шаверма ва сыр.',
    'category-pizza': 'Пицца',
    'name-pizza1': 'Пицца Маргарита',
    'desc-pizza1': '30 см',
    'name-pizza2': 'Груша дор блю',
    'desc-pizza2': '30 см',
    'name-pizza3': 'Гавайский',
    'desc-pizza3': '30см',
    'name-pizza4': 'Курица грибы',
    'desc-pizza4': 'Пиццаи классикӣ бо соуси томатӣ, моцарелла ва помидорҳои тару тоза.',
    'name-pizza5': 'Пеперони',
    'desc-pizza5': 'Пиццаи классикӣ бо соуси томатӣ, моцарелла ва помидорҳои тару тоза.',
    'name-pizza6': 'Safar фирминий 55см',
    'desc-pizza6': 'Пиццаи классикӣ бо соуси томатӣ, моцарелла ва помидорҳои тару тоза.',
    'name-pizza7': '4 сезона',
    'desc-pizza7': 'Пиццаи классикӣ бо соуси томатӣ, моцарелла ва помидорҳои тару тоза.',
    'name-pizza8': 'Пицца Маргарита',
    'desc-pizza8': 'Пиццаи классикӣ бо соуси томатӣ, моцарелла ва помидорҳои тару тоза.',
    'name-pizza9': '4 сыра',
    'desc-pizza9': 'Пиццаи классикӣ бо соуси томатӣ, моцарелла ва помидорҳои тару тоза.',
    'name-pizza10': 'Мясная',
    'desc-pizza10': 'Пиццаи классикӣ бо соуси томатӣ, моцарелла ва помидорҳои тару тоза.',
    'name-pizza11': 'Цыплёнок ранч',
    'desc-pizza11': 'Пиццаи классикӣ бо соуси томатӣ, моцарелла ва помидорҳои тару тоза.',
    'name-pizza12': 'Трюфельная',
    'desc-pizza12': 'Пиццаи классикӣ бо соуси томатӣ, моцарелла ва помидорҳои тару тоза.',
    'category-salads': 'Салатҳо',
    'name-salad1': 'Салати юнонӣ',
    'desc-salad1': 'ририр',
    'name-salad2': 'Салати японӣ',
    'desc-salad2': 'ририр',
    'name-salad3': 'Салати Цезарь бо куриные',
    'desc-salad3': 'ририр',
    'name-salad4': 'Салати аз баклажан',
    'desc-salad4': 'ририр',
    'category-drinks': 'Нӯшокиҳо',
    'name-drink1': 'Gorilla 0.33 мл',
    'desc-drink1': 'Нӯшокии энергетикӣ.',
    'name-drink2': 'Adrenaline 0.25 мл',
    'desc-drink2': 'Нӯшокии энергетикӣ.',
    'name-drink3': 'RC кола 1 л',
    'desc-drink3': 'Нӯшокии газдор.',
    'name-drink4': 'Pepsi 1 л',
    'desc-drink4': 'Нӯшокии газдор.',
    'name-drink5': 'Мохито 0.5 л',
    'desc-drink5': 'Нӯшокии освежающий бо вкусҳои гуногун.',
    'name-drink6': 'Bon aqua 0.5 л',
    'desc-drink6': 'Оби нӯшокӣ.',
    'name-drink7': 'Чай фюсти 0.5 л',
    'desc-drink7': 'Чойи сард.',
    'name-drink8': 'Натуральный Сок пико 1 л',
    'desc-drink8': 'Шарбати мевагӣ.',
    'name-drink9': 'Fanta 1 л',
    'desc-drink9': 'Нӯшокии газдор.',
    'name-drink10': 'Coca Cola 0.5',
    'desc-drink10': 'Нӯшокии газдор.',
    'name-drink11': 'Тропик 0.5',
    'desc-drink11': 'Нӯшокии освежающий. Апельсини ширин.',
    'category-sauces': 'Соусҳо',
    'name-sauce1': 'Соуси чесночный',
    'desc-sauce1': 'Соуси чесночный 35г.',
    'name-sauce2': 'Соуси острый',
    'desc-sauce2': 'Соуси острый 35г.',
    'name-sauce3': 'Соуси сырный',
    'desc-sauce3': 'Соуси сырный 35г.',
    'category-other': 'Дигар',
    'name-other1': 'Котлета аз говядина 100г',
    'desc-other1': 'Котлета аз говядина.',
    'name-other2': 'Сыри плавленый 1д',
    'desc-other2': 'Сыри плавленый.',
    'name-other3': 'Перец халапеньо 15г',
    'desc-other3': 'Острый маринованный перец халапеньо.',
    'name-other4': 'Булочка',
    'desc-other4': 'Булочкаи тару тоза барои бургерҳо.',
    'special-subtitle': 'Интиқол ва пардохт',
    'special-title': 'Чӣ тавр фармоиш ва пардохт кардан',
    'special-description': 'Интиқоли зуд дар ҳудуди Пенҷикент ва тарзҳои қулайи пардохт барои раҳатии шумо.',
    'delivery-title': 'Интиқол',
    'delivery-subtitle': 'Аз 9:00 то 22:00',
    'delivery-feature1': 'Интиқоли ройгон ҳангоми фармоиш аз 50 TJS',
    'delivery-feature2': 'Интиқол фақат дар ҳудуди Пенҷикент',
    'delivery-feature3': 'Фармоишҳо тавассути телефон ё шабакаҳои иҷтимоӣ қабул мешаванд',
    'delivery-feature4': 'Тамосҳо барои интиқол: +992 928 082 552, +992 970 882 552',
    'order-delivery': 'Фармоиш интиқол',
    'badge-fast': 'Зуд ва қулай',
    'payment-title': 'Пардохт ва дастгирии техникӣ',
    'payment-subtitle': 'Тарзҳои қулайи пардохт',
    'payment-feature1': 'Пардохт тавассути Алиф',
    'payment-feature2': 'Пардохт тавассути Душанбе Сити',
    'payment-feature3': 'Пардохт бо пулҳои нақд ҳангоми гирифтан',
    'payment-feature4': 'Дастгирии техникӣ: WhatsApp 7 (996)5450272',
    'contact-support': 'Бо дастгирӣ тамос гиред',
    'badge-always': 'Ҳамеша дар тамос',
    'about-subtitle': 'Таърихи мо',
    'about-title': 'Кафе SaFar',
    'about-text1': 'Кафе SaFar дар Пенҷикент - ин ҷоест, ки фастфуд ба санъат табдил меёбад. Мо ингредиентҳои тару тозаи маҳаллиро истифода мекунем, барои эҷоди таомҳои болаззат ва сифатнок.',
    'about-text2': 'Мо бо интиқоли зуд ва диққат ба ҳар фармоиш фахр мекунем. Аз бургерҳои ширин то стрипсҳои хрустящ - ҳама бо ҷон пухта мешавад.',
    'about-feature-title1': 'Ингредиентҳои тару тоза',
    'about-feature-text1': 'Фақат маҳсулоти маҳаллии сифатнок истифода мешаванд.',
    'about-feature-title2': 'Рецептҳои уникалӣ',
    'about-feature-text2': 'Таомҳои болаззат, бо ғамхорӣ эҷод шуда.',
    'about-feature-title3': 'Интиқоли зуд',
    'about-feature-text3': 'Интиқол дар ҳудуди Пенҷикент аз 50 TJS ройгон.',
    'about-feature-title4': 'Бо муҳаббат',
    'about-feature-text4': 'Ҳар таом бо ғамхорӣ пухта шудааст.',
    'about-badge': 'Аз соли 2023',
    'order-title': 'Омодаед фастфуди болаззатро санҷед?',
    'order-text': 'Онлайн фармоиш бо интиқол ё худгирӣ ва аз таомҳои мо дар хона ё офис лаззат баред.',
    'order-btn': 'Фармоиш',
    'footer-text': 'Кафе SaFar - ин фастфуди болаззат бо ингредиентҳои маҳаллӣ ва интиқоли зуд дар Пенҷикент.',
    'footer-heading1': 'Пайвандҳои зуд',
    'footer-heading2': 'Соатҳои кор',
    'opening-cafe': 'Кафе: 08:00 - 23:00',
    'opening-delivery': 'Интиқол: 09:00 - 22:00',
    'footer-heading3': 'Тамосҳо',
    'contact-address': 'Проспекти Рӯдакӣ 112, Пенҷикент, Тоҷикистон',
    'contact-support': ' Дастгирии техникӣ',
    'footer-copyright': '&copy; 2025 Кафе SaFar. |  Таҳия <a href="https://t.me/xalilov_uc">Sino IT </a>',
    'cart-title': 'Корзинаи шумо',
    'cart-total': 'Ҷамъ:',
    'label-name': 'Номи шумо',
    'placeholder-name': 'номи худро нависед',
    'label-phone': 'Телефон',
    'label-order-type': 'Навъи фармоиш',
    'button-delivery': 'Интиқол',
    'button-pickup': 'Худгирӣ',
    'label-address': 'Суроғаи интиқол',
    'placeholder-address': 'суроғаи худро нависед',
    'label-pickup': 'Ҷои худгирӣ',
    'pickup-option1': 'Болои дедсати сказка',
    'pickup-option2': 'Пеши мактаби 15',
    'pickup-option3': ' ру ба руи  меҳру муҳаббат пиццерия ',
    'label-payment': 'Тарзи пардохт',
    'payment-cash': 'Нақд',
    'payment-ds': 'Душанбе Сити',
    'payment-alif': 'Алиф',
    'label-comments': 'Шарҳ ба фармоиш',
    'placeholder-comments': 'шарҳ дар бораи фармоиш нависед (метавонед гузаред!)',
    'order-total': 'Барои пардохт:',
    'submit-order': 'Фармоишро тасдиқ кунед',
    "login": "Даромад",
  },
  zh: {
    'nav-home': '首页',
    'nav-menu': '菜单',
    'nav-special': '配送和支付',
    'nav-about': '关于我们',
    'nav-contact': '联系方式',
    'search-placeholder': '搜索菜肴...',
    'order-online': '在线订购',
    'hero-subtitle': '美味快餐',
    'hero-title-part1': '汉堡和 ',
    'hero-title-part2': '美味',
    'hero-title-part3': ' 菜肴',
    'hero-description': 'SaFar 咖啡厅提供使用当地食材的高品质快餐，并在彭吉肯特提供快速送货。',
    'view-menu': '查看菜单',
    'menu-subtitle': '我们的菜单',
    'menu-title': '美味快餐',
    'menu-description': '查看我们的菜单：从多汁汉堡到脆皮条和清凉饮料。',
    'tab-all': '所有',
    'tab-combo': '组合',
    'tab-burgers': '汉堡',
    'tab-hotdogs': '热狗',
    'tab-strips': '条',
    'tab-sauces': '酱汁',
    'tab-drinks': '饮料',
    'tab-pizza': '比萨',
    'tab-salads': '沙拉',
    'tab-other': '其他',
    'badge-hit': '热销',
    'category-combo': '组合',
    'name-combo1': '组合汉堡 5 在 1',
    'desc-combo1': '1 个鸡肉汉堡, 125克薯条, 250克混合, 1份可选酱, 1 份可乐或芬达 0.5.',
    'name-combo2': '组合 3 在 1',
    'desc-combo2': '1 个鸡肉汉堡, 125克薯条, 1 份可乐或芬达 0.5.',
    'name-combo3': '组合 X 3 在 1',
    'desc-combo3': '1 个牛肉汉堡, 125克薯条, 1 份可乐或芬达 0.5.',
    'name-combo4': '组合 Asia',
    'desc-combo4': '125克咬, 70克薯条, 2份煎香肠, 1份果汁 200ml, 1份可选酱.',
    'name-combo5': '组合 5 在 1',
    'desc-combo5': '1 个芝麻面包, 250克混合部分, 125克薯条, 1份可选酱, 1 份可乐或芬达 0.5.',
    'name-combo6': '朋友盒',
    'desc-combo6': '1 个牛肉汉堡, 1 个鸡肉汉堡, 125克薯条, 250克混合部分, 2 份可选酱, 1 份 Rc 可乐 1l.',
    'name-combo7': '篮子组合 2X',
    'desc-combo7': '2 x 250克混合部分, 2 x 125克薯条, 2 份可选酱, 2 份可乐或芬达 0.5.',
    'category-fri': '薯条',
    'name-fri1': '薯条配香肠和酱',
    'desc-fri1': '150克薯条, 2份香肠和2种可选酱.',
    'name-fri2': '薯条配炖肉',
    'desc-fri2': '150克薯条, 70克可选炖肉(牛肉/鸡肉).',
    'name-fri3': '薯条配酱',
    'desc-fri3': '150克薯条, 2种可选酱.',
    'name-fri4': '乡村土豆',
    'desc-fri4': '125克乡村土豆.',
    'name-fri5': '薯条',
    'desc-fri5': '125克份薯条.',
    'badge-popular': '受欢迎',
    'category-strips': '条',
    'name-strips1': '篮子腿 1KG',
    'desc-strips1': '小鸡腿在脆皮面包屑中. 中等辣度.',
    'name-strips2': '腿 250G',
    'desc-strips2': '多汁鸡腿在份包装中. 中等辣度.',
    'name-strips3': '篮子翅 1kg',
    'desc-strips3': '鸡翅在脆皮面包屑中. 中等辣度.',
    'name-strips4': '条 250g',
    'desc-strips4': '鸡条在份包装中.',
    'name-strips5': '篮子咬 1kg',
    'desc-strips5': '大份脆咬. 不辣.',
    'name-strips6': '块 250g',
    'desc-strips6': '鸡块在份包装中. 不辣.',
    'name-strips8': '篮子块 1kg',
    'desc-strips8': '大份鸡块. 不辣.',
    'name-strips9': '翅 250g',
    'desc-strips9': '鸡翅在份包装中.',
    'name-strips10': '混合 250g',
    'desc-strips10': '混合份, 由鸡腿, 翅, 条和多汁咬组成.',
    'name-strips11': '篮子混合 1kg',
    'desc-strips11': '大份混合从鸡腿, 翅, 条和咬.',
    'category-burgers': '汉堡',
    'name-burger1': '双芝士汉堡',
    'desc-burger1': '面包, 签名蛋黄酱酱, 2牛肉饼, 黄瓜, 洋葱, 融化芝士, 番茄, 大蒜酱.',
    'name-burger2': '拉瓦什汉堡',
    'desc-burger2': '不寻常汉堡, 用拉瓦什包裹牛肉饼, 芝士和Lay\'s薯片.',
    'name-burger3': '双汉堡',
    'desc-burger3': '面包, 签名蛋黄酱酱, 2牛肉饼, 黄瓜, 洋葱, 融化芝士, 番茄, 大蒜酱.',
    'name-burger5': '鸡汉堡',
    'desc-burger5': '汉堡配鸡条.',
    'name-burger6': '鸡芝士',
    'desc-burger6': '汉堡配鸡饼和芝士.',
    'name-burger7': '牛肉 & 鸡肉',
    'desc-burger7': '汉堡配牛肉和鸡肉饼和芝士.',
    'name-burger8': '凯撒汉堡',
    'desc-burger8': '汉堡配鸡肉和凯撒酱.',
    'name-burger9': '芝士汉堡',
    'desc-burger9': '经典汉堡配芝士.',
    'name-burger10': '汉堡',
    'desc-burger10': '经典汉堡配多汁饼.',
    'name-burger11': 'Panj kent 汉堡',
    'desc-burger11': '经典汉堡配多汁饼.',
    'category-hotdogs': '热狗',
    'name-hotdog1': '热狗 SaFar',
    'desc-hotdog1': '热狗配多汁香肠和酱.',
    'name-hotdog3': '热狗 Longer',
    'desc-hotdog3': '长热狗配多汁香肠.',
    'name-hotdog5': '热狗 Grill',
    'desc-hotdog5': '热狗配在烤架上煮的香肠.',
    'name-hotdog6': '热狗 Standard',
    'desc-hotdog6': '经典热狗.',
    'name-hotdog7': '热狗 Mini',
    'desc-hotdog7': '经典热狗.',
    'name-hotdog8': '热烤肉',
    'desc-hotdog8': '经典热狗.',
    'name-hotdog9': '热狗 Panj kent',
    'desc-hotdog9': '经典热狗.',
    'name-hotdog10': '热狗 BBQ',
    'desc-hotdog10': '热狗配BBQ酱.',
    'category-shaverma': '沙威玛',
    'name-shaverma1': '扭沙威玛',
    'desc-shaverma1': '扭配沙威玛填充.',
    'name-shaverma2': '扭',
    'desc-shaverma2': '经典扭配鸡肉.',
    'name-shaverma3': '扭辣',
    'desc-shaverma3': '辣扭配鸡肉.',
    'name-shaverma4': '扭沙威玛芝士',
    'desc-shaverma4': '扭配沙威玛和芝士.',
    'name-shaverma5': '扭芝士',
    'desc-shaverma5': '扭配沙威玛和芝士.',
    'name-shaverma6': 'Tan Tuni 配鸡肉',
    'desc-shaverma6': '扭配沙威玛和芝士.',
    'name-shaverma7': 'Tan Tuni 配牛肉',
    'desc-shaverma7': '扭配沙威玛和芝士.',
    'category-pizza': '比萨',
    'name-pizza1': '比萨 Margherita',
    'desc-pizza1': '30 厘米',
    'name-pizza2': '梨 Dor Blue',
    'desc-pizza2': '30 厘米',
    'name-pizza3': '夏威夷',
    'desc-pizza3': '30厘米',
    'name-pizza4': '鸡肉蘑菇',
    'desc-pizza4': '经典比萨配番茄酱, 马苏里拉和新新鲜番茄.',
    'name-pizza5': '意大利辣香肠',
    'desc-pizza5': '经典比萨配番茄酱, 马苏里拉和新新鲜番茄.',
    'name-pizza6': 'Safar 签名 55厘米',
    'desc-pizza6': '经典比萨配番茄酱, 马苏里拉和新新鲜番茄.',
    'name-pizza7': '4 季节',
    'desc-pizza7': '经典比萨配番茄酱, 马苏里拉和新新鲜番茄.',
    'name-pizza8': '比萨 Margherita',
    'desc-pizza8': '经典比萨配番茄酱, 马苏里拉和新新鲜番茄.',
    'name-pizza9': '4 芝士',
    'desc-pizza9': '经典比萨配番茄酱, 马苏里拉和新新鲜番茄.',
    'name-pizza10': '肉',
    'desc-pizza10': '经典比萨配番茄酱, 马苏里拉和新新鲜番茄.',
    'name-pizza11': '鸡肉牧场',
    'desc-pizza11': '经典比萨配番茄酱, 马苏里拉和新新鲜番茄.',
    'name-pizza12': '松露',
    'desc-pizza12': '经典比萨配番茄酱, 马苏里拉和新新鲜番茄.',
    'category-salads': '沙拉',
    'name-salad1': '希腊沙拉',
    'desc-salad1': 'ririr',
    'name-salad2': '日本沙拉',
    'desc-salad2': 'ririr',
    'name-salad3': '鸡肉凯撒沙拉',
    'desc-salad3': 'ririr',
    'name-salad4': '茄子沙拉',
    'desc-salad4': 'ririr',
    'category-drinks': '饮料',
    'name-drink1': 'Gorilla 0.33 毫升',
    'desc-drink1': '能量饮料.',
    'name-drink2': 'Adrenaline 0.25 毫升',
    'desc-drink2': '能量饮料.',
    'name-drink3': 'RC 可乐 1 升',
    'desc-drink3': '碳酸饮料.',
    'name-drink4': 'Pepsi 1 升',
    'desc-drink4': '碳酸饮料.',
    'name-drink5': '莫吉托 0.5 升',
    'desc-drink5': '清凉饮料有各种口味.',
    'name-drink6': 'Bon aqua 0.5 升',
    'desc-drink6': '饮用水.',
    'name-drink7': 'Fusti 茶 0.5 升',
    'desc-drink7': '冷茶.',
    'name-drink8': '天然 Pico 果汁 1 升',
    'desc-drink8': '水果汁.',
    'name-drink9': 'Fanta 1 升',
    'desc-drink9': '碳酸饮料.',
    'name-drink10': 'Coca Cola 0.5',
    'desc-drink10': '碳酸饮料.',
    'name-drink11': 'Tropic 0.5',
    'desc-drink11': '清凉饮料. 多汁橙子.',
    'category-sauces': '酱汁',
    'name-sauce1': '大蒜酱',
    'desc-sauce1': '大蒜酱 35克.',
    'name-sauce2': '辣酱',
    'desc-sauce2': '辣酱 35克.',
    'name-sauce3': '芝士酱',
    'desc-sauce3': '芝士酱 35克.',
    'category-other': '其他',
    'name-other1': '牛肉饼 100克',
    'desc-other1': '牛肉饼.',
    'name-other2': '融化芝士 1片',
    'desc-other2': '融化芝士.',
    'name-other3': '哈拉佩诺椒 15克',
    'desc-other3': '辣腌哈拉佩诺椒.',
    'name-other4': '面包',
    'desc-other4': '新鲜汉堡面包.',
    'special-subtitle': '配送和支付',
    'special-title': '如何订购和支付',
    'special-description': '在彭吉肯特范围内快速配送和方便的支付方式以您的舒适.',
    'delivery-title': '配送',
    'delivery-subtitle': '从 9:00 到 22:00',
    'delivery-feature1': '订单从 50 TJS 免费配送',
    'delivery-feature2': '仅在彭吉肯特范围内配送',
    'delivery-feature3': '通过电话或社交网络接受订单',
    'delivery-feature4': '配送联系方式: +992 928 082 552, +992 970 882 552',
    'order-delivery': '订购配送',
    'badge-fast': '快速方便',
    'payment-title': '支付和技术支持',
    'payment-subtitle': '方便的支付方式',
    'payment-feature1': '通过 Alif 支付',
    'payment-feature2': '通过 Dushanbe City 支付',
    'payment-feature3': '收到时现金支付',
    'payment-feature4': '技术支持: WhatsApp +7 (996)5450272',
    'contact-support': '联系支持',
    'badge-always': '始终在线',
    'about-subtitle': '我们的故事',
    'about-title': 'SaFar 咖啡厅',
    'about-text1': '彭吉肯特的 SaFar 咖啡厅是一个快餐变成艺术的地方。我们使用新鲜当地食材创造美味和高品质菜肴.',
    'about-text2': '我们以快速配送和对每个订单的关注而自豪。从多汁汉堡到脆皮条 - 一切都用心准备.',
    'about-feature-title1': '新鲜食材',
    'about-feature-text1': '仅使用高品质当地产品.',
    'about-feature-title2': '独特食谱',
    'about-feature-text2': '美味菜肴用心创建.',
    'about-feature-title3': '快速配送',
    'about-feature-text3': '彭吉肯特范围内从 50 TJS 免费配送.',
    'about-feature-title4': '用心',
    'about-feature-text4': '每道菜都用心准备.',
    'about-badge': '自 2023 年',
    'order-title': '准备尝试美味快餐吗?',
    'order-text': '在线订购带配送或自取, 在家或办公室享受我们的菜肴.',
    'order-btn': '订购',
    'footer-text': 'SaFar 咖啡厅是使用当地食材的美味快餐和在彭吉肯特的快速配送.',
    'footer-heading1': '快速链接',
    'footer-heading2': '工作时间',
    'opening-cafe': '咖啡厅: 08:00 - 23:00',
    'opening-delivery': '配送: 09:00 - 22:00',
    'footer-heading3': '联系方式',
    'contact-address': 'Rudaki 大道 112, 彭吉肯特, 塔吉克斯坦',
    'contact-support': ' 技术支持',
    'footer-copyright': '&copy; 2025 SaFar 咖啡厅.  | 开发 <a href="https://t.me/xalilov_uc">Sino IT </a>',
    'cart-title': '您的购物车',
    'cart-total': '总计:',
    'label-name': '您的名字',
    'placeholder-name': '写你的名字',
    'label-phone': '电话',
    'label-order-type': '订单类型',
    'button-delivery': '配送',
    'button-pickup': '自取',
    'label-address': '配送地址',
    'placeholder-address': '写你的地址',
    'label-pickup': '自取地点',
    'pickup-option1': 'Bolo i ded sati skazka',
    'pickup-option2': 'Peshi makta bi 15',
    'pickup-option3': 'Roo ba rooi mehru muhabbat pizzeria',
    'label-payment': '支付方式',
    'payment-cash': '现金',
    'payment-ds': 'Dushanbe City',
    'payment-alif': 'Alif',
    'label-comments': '订单评论',
    'placeholder-comments': '写订单评论(可以跳过!)',
    'order-total': '支付:',
    'submit-order': '下订单',
    "login": "登录",
  }
};

// Переключение языка с сохранением в localStorage
function switchLanguage(lang) {
  document.querySelectorAll('[data-translate]').forEach(el => {
    const key = el.dataset.translate;
    if (translations[lang] && translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });
  
  document.querySelectorAll('[data-translate-placeholder]').forEach(el => {
    const key = el.dataset.translatePlaceholder;
    if (translations[lang] && translations[lang][key]) {
      el.placeholder = translations[lang][key];
    }
  });
  
  document.documentElement.lang = lang;
  
  // Сохраняем выбранный язык в localStorage
  localStorage.setItem('preferredLanguage', lang);
}

// Глобальная функция для смены языка (используется в script.js)
window.changeLanguage = function(lang) {
  switchLanguage(lang);
};

// Инициализация языка при загрузке
document.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem('preferredLanguage') || 'ru';
  switchLanguage(savedLang);
  
  // Обновляем компактный языковой селектор
  updateCompactLanguageSelector(savedLang);
});

// Функция обновления компактного языкового селектора
function updateCompactLanguageSelector(lang) {
  const compactSelector = document.querySelector('.compact-language-selector');
  if (!compactSelector) return;
  
  const btn = compactSelector.querySelector('.compact-language-btn span:not(.compact-language-flag)');
  const items = compactSelector.querySelectorAll('.compact-language-item');
  
  if (btn) {
    // Обновляем кнопку
    btn.textContent = lang.toUpperCase();
  }
  
  // Обновляем активный элемент в выпадающем списке
  items.forEach(item => {
    item.classList.remove('active');
    if (item.dataset.lang === lang) {
      item.classList.add('active');
    }
  });
}